# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-04 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(choices=[('beauty', 'beauty'), ('daily', 'daily'), ('art', 'art'), ('food', 'food'), ('culture', 'culture'), ('scenery', 'scenery')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='picha/')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('category', models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.CASCADE, to='pics.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locname', models.CharField(choices=[('nairobi', 'nairobi'), ('naivasha', 'naivasha'), ('watamu', 'watamu'), ('kisumu', 'kisumu'), ('nyeri', 'nyeri'), ('kitale', 'kitale')], max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.CASCADE, to='pics.Location'),
        ),
    ]
