# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-04 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catname',
            field=models.CharField(choices=[('party', 'party'), ('daily', 'daily'), ('art', 'art'), ('comics', 'comics'), ('culture', 'culture'), ('scenery', 'scenery')], max_length=40),
        ),
        migrations.AlterField(
            model_name='location',
            name='locname',
            field=models.CharField(choices=[('nairobi', 'nairobi'), ('somewhere', 'somewhere'), ('belgium', 'belgium'), ('wild', 'wild'), ('france', 'france'), ('mombasa', 'mombasa')], max_length=40),
        ),
    ]
