# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-04 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0002_auto_20200204_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
